
spring.datasource.url=jdbc:mariadb://localhost/form_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=momoouadii1998@gmail.com
spring.mail.password=wwwkfkjaotdfziwb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.url=http://localhost:8080
app.front=